package com.tiket.tix.gateway.entity.constant;

public interface PrivilegeId {
  String GET_PROMO_LIST = "300";
  String CREATE_PROMO_LIST = "301";
  String UPDATE_PROMO_LIST = "302";
  String REQUEST_APPROVAL_PROMO_LIST = "303";
  String ACTIVATE_PROMO_LIST = "304";
  String UNACTIVATE_PROMO_LIST = "305";
  String DELETE_PROMO_LIST = "306";
  String GET_PROMO_CATEGORY = "310";
  String CREATE_PROMO_CATEGORY = "311";
  String UPDATE_PROMO_CATEGORY = "312";
  String DELETE_PROMO_CATEGORY = "313";
  String MM_MODULE = "207";
  String HOLIDAY = "207";
  String CREATE_IMAGES = "301";

  String CREATE_PROMO_CODE = "320";
  String FIND_BY_ID_PROMO_CODE = "321";
  String GET_PROMO_CODE = "326";
  String ACTIVATE_PROMO_CODE = "322";
  String UNACTIVATE_PROMO_CODE = "323";

  String UPDATE_PROMO_CODE = "324";
  String DELETE_PROMO_CODE = "325";


  String CREATE_CAMPAIGN = "330";
  String FIND_BY_ID_CAMPAIGN = "331";
  String GET_CAMPAIGN = "332";

  String ACTIVATE_CAMPAIGN = "337";
  String UNACTIVATE_CAMPAIGN = "338";
  String PENDING_CAMPAIGN = "336";
  String REJECTED_CAMPAIGN = "339";

  String UPDATE_CAMPAIGN = "333";
  String DELETE_CAMPAIGN = "334";
  String FIND_CAMPAIGN_ACTIVATE = "340";

  String CREATE_PROMO_ADJUSTMENT = "350";
  String FIND_BY_ID_PROMO_ADJUSTMENT = "351";
  String GET_PROMO_ADJUSTMENT = "352";

  String ACTIVATE_PROMO_ADJUSTMENT = "353";
  String UNACTIVATE_PROMO_ADJUSTMENT = "354";
  String PENDING_PROMO_ADJUSTMENT = "355";
  String REJECTED_PROMO_ADJUSTMENT = "357";

  String UPDATE_PROMO_ADJUSTMENT = "358";
  String DELETE_PROMO_ADJUSTMENT = "359";
  String FIND_PROMO_ADJUSTMENT_ACTIVATE = "360";

  String CREATE_VARIABLE = "370";
  String FIND_BY_ID_VARIABLE = "371";
  String GET_VARIABLE = "372";

  String UPDATE_VARIABLE = "373";
  String DELETE_VARIABLE = "374";


  String CREATE_PRODUCT_TYPE = "380";
  String FIND_BY_ID_PRODUCT_TYPE = "381";
  String GET_PRODUCT_TYPE = "382";

  String UPDATE_PRODUCT_TYPE = "383";
  String DELETE_PRODUCT_TYPE = "384";
  String FIND_PRODUCT_TYPE = "385";


  String CREATE_BIN_NUMBER = "390";
  String FIND_BY_ID_BIN_NUMBER = "391";
  String GET_BIN_NUMBER = "392";

  String UPDATE_BIN_NUMBER = "393";
  String DELETE_BIN_NUMBER = "394";
  String FIND_BIN_NUMBER = "395";

  String FIND_ALL_BANK = "400";
  String FIND_ALL_PAYMENT = "410";
  String FIND_ALL_STORE_ID = "420";
  String FIND_ALL_CARD_TYPE = "440";
  String FIND_ALL_VARIABLE = "450";
  String FIND_ALL_CHANNEL_ID = "460";

  String CREATE_BUSINESS_LOGIC_RESPONSE = "470";
  String FIND_BY_ID_BUSINESS_LOGIC_RESPONSE = "471";
  String GET_BUSINESS_LOGIC_RESPONSE = "472";

  String UPDATE_BUSINESS_LOGIC_RESPONSE = "473";
  String DELETE_BUSINESS_LOGIC_RESPONSE = "474";
  String FIND_ALL_BUSINESS_LOGIC_RESPONSE = "475";


  String FIND_VARIABLE_SOURCE = "480";

  String CREATE_ADJUSTMENT_RULE = "490";
  String FIND_BY_ID_ADJUSTMENT_RULE = "491";
  String GET_ADJUSTMENT_RULE = "492";

  String UPDATE_ADJUSTMENT_RULE = "493";
  String DELETE_ADJUSTMENT_RULE = "494";

  String ACTIVATE_ADJUSTMENT_RULE = "495";
  String UNACTIVATE_ADJUSTMENT_RULE = "496";
  String PENDING_ADJUSTMENT_RULE = "497";
  String REJECTED_ADJUSTMENT_RULE = "498";

  String CREATE_ADJUSTMENT_DETAIL = "500";
  String FIND_BY_ID_ADJUSTMENT_DETAIL = "501";
  String GET_ADJUSTMENT_DETAIL = "502";

  String UPDATE_ADJUSTMENT_DETAIL = "503";
  String DELETE_ADJUSTMENT_DETAIL = "504";



  String CREATE_BANNER_CATEGORY = "510";
  String FIND_BY_ID_BANNER_CATEGORY = "511";
  String GET_BANNER_CATEGORY = "512";

  String UPDATE_BANNER_CATEGORY = "513";
  String DELETE_BANNER_CATEGORY = "514";
  String FIND_ALL_BANNER_CATEGORY = "515";

  String CREATE_BANNER= "520";
  String FIND_BY_ID_BANNER= "521";
  String GET_BANNER = "522";

  String UPDATE_BANNER = "523";
  String DELETE_BANNER = "524";
  String ACTIVATE_BANNER = "525";
  String UNACTIVATE_BANNER = "526";
  String PENDING_BANNER = "527";
  String REJECTED_BANNER = "528";

  String CREATE_FLIGHT_DISTRIBUTION = "530";
  String FIND_BY_ID_FLIGHT_DISTRIBUTION = "531";
  String GET_FLIGHT_DISTRIBUTION = "532";
  String UPDATE_FLIGHT_DISTRIBUTION = "533";
  String DELETE_FLIGHT_DISTRIBUTION = "534";
  String ACTIVATE_FLIGHT_DISTRIBUTION = "535";
  String UNACTIVATE_FLIGHT_DISTRIBUTION = "536";

  String CREATE_PREFERRED_AIRLINES = "540";
  String FIND_BY_ID_PREFERRED_AIRLINES = "541";
  String GET_PREFERRED_AIRLINES = "542";
  String UPDATE_PREFERRED_AIRLINES = "543";
  String DELETE_PREFERRED_AIRLINES = "544";
  String ACTIVATE_PREFERRED_AIRLINES = "545";
  String UNACTIVATE_PREFERRED_AIRLINES = "546";

  String CREATE_FLIGHT_CACHE_RULE = "550";
  String FIND_BY_ID_FLIGHT_CACHE_RULE = "551";
  String GET_FLIGHT_CACHE_RULE = "552";
  String UPDATE_FLIGHT_CACHE_RULE = "553";
  String DELETE_FLIGHT_CACHE_RULE = "554";

  String FIND_ALL_AIRPORT_RULE = "560";
  String FIND_ALL_AIRLINE_RULE = "570";
  String FIND_ALL_SUPPLIER_MASTER_RULE = "580";

  String FIND_ALL_AIRPORT_RME = "590";
  String FIND_ALL_AIRLINE_RME = "600";
  String FIND_ALL_SUPPLIER_MASTER_RME = "610";
}
